# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0002_bank'),
        ('person', '0003_auto_20160118_2210'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=64)),
                ('billing_andress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_billing_andress', to='person.Address')),
                ('items', models.ManyToManyField(to='item.Item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('transfered', models.DateTimeField()),
                ('reconcilated', models.DateTimeField()),
                ('external_reference', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fee_transsaction_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fee_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('statement_descriptor', models.CharField(max_length=64)),
                ('installments', models.IntegerField()),
                ('notification_url', models.CharField(max_length=256)),
                ('success_url', models.CharField(max_length=256)),
                ('failure_url', models.CharField(max_length=256)),
                ('user_agent', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=64)),
                ('cookie', models.CharField(max_length=1024)),
                ('device_session_id', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing_address', to='person.Address')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=128)),
                ('ssl_img', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('cc_token', models.CharField(max_length=64)),
                ('masked_cc', models.CharField(max_length=16)),
                ('authorization', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('error_code', models.IntegerField()),
                ('error_message', models.CharField(max_length=128)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payment')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Reconcilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seller_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=64)),
                ('transfer_number', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Bank')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('params', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('payment_method', models.ManyToManyField(to='seller.Payment_method')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Processor')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_transfered', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
                ('deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller_bank')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payer')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='banks',
            field=models.ManyToManyField(through='seller.Seller_bank', to='currency.Bank'),
        ),
        migrations.AddField(
            model_name='seller',
            name='items',
            field=models.ManyToManyField(to='item.Item'),
        ),
        migrations.AddField(
            model_name='seller',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
        migrations.AddField(
            model_name='seller',
            name='shares',
            field=models.ManyToManyField(to='seller.Fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(through='seller.Payment_items', to='item.Item'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payment_method'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconcilation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Reconcilation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Address'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Transfer'),
        ),
        migrations.AddField(
            model_name='payer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_menthod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Payment_method'),
        ),
        migrations.AddField(
            model_name='fee',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Terminal'),
        ),
        migrations.AddField(
            model_name='bin',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='bin',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Terminal'),
        ),
    ]
