# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='person.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
