# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ManyToManyField(to='person.Address'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
