# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ManyToManyField(blank=True, to='person.Address'),
        ),
    ]
