INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	#'oauth2_provider',
	'corsheaders',
	'rest_framework',
	'rest_framework.authtoken',
	'users',
	'person',
	'currency',
	'item',
)
